version: '3.8'

services:
  web:
    build: .
    ports:
      - "8081:80"
    volumes:
      - ./css:/usr/share/nginx/html/css
      - ./js:/usr/share/nginx/html/js
      - ./images:/usr/share/nginx/html/images
      - ./index.html:/usr/share/nginx/html/index.html
    restart: always
